# Copyright 2017 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------------

version: '3.3'

services:

  to0scheduler:
    image: to0scheduler
    container_name: to0scheduler
    expose:
      - 8049
    ports:
      - '8049:8049'
    build:
      context: .
      dockerfile: to0scheduler/Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    environment:
      - 'http_proxy=${http_proxy}'
      - 'https_proxy=${https_proxy}'
      - 'no_proxy=${no_proxy}'
    network_mode: host
    
  ocs:
    image: ocs
    container_name: owner-companion-service
    expose:
      - 9009
    ports:
      - '9009:9009'
    depends_on:
      - to0scheduler
    build:
      context: .
      dockerfile: ocs/Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    environment:
      - 'http_proxy=${http_proxy}'
      - 'https_proxy=${https_proxy}'
      - 'no_proxy=${no_proxy}'
    volumes:
      - ./ocs/config/db:/ocs/config/db
    network_mode: host

  ops:
    image: ops
    container_name: owner-protocol-service
    expose:
      - 8042
    ports:
      - '8042:8042'
    depends_on:
      - ocs
    build:
      context: .
      dockerfile: ops/Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    environment:
      - 'http_proxy=${http_proxy}'
      - 'https_proxy=${https_proxy}'
      - 'no_proxy=${no_proxy}'
    network_mode: host
